package view.windows;

import java.io.Serializable;
import javax.swing.JFrame;
import javax.swing.JTable;

/**
 *
 * @author Lockland
 */
public class ProgramFrm extends JFrame implements Serializable{

    ViewProduto viewProduto;
    ViewCliente viewCliente;
    ViewVendas viewCompras;
    /**
     * Creates new form ProgramFrm
     */
    public ProgramFrm() {
        setTitle("Sales-Manager");
        initComponents();
        createPanels();
        addPanelsToMainPanel();
        setLocationRelativeTo(null);
    }
    
    private void createPanels(){
        viewProduto = new ViewProduto();
        viewCliente = new ViewCliente();
        viewCompras = new ViewVendas();
    }
    
    private void addPanelsToMainPanel(){
        panelBox.removeAll();
        panelBox.add(viewProduto);
        panelBox.add(viewCliente);
        panelBox.add(viewCompras);
    }
    
    private void hideAllPanels(){
        viewProduto.setVisible(false);
        viewCliente.setVisible(false);
        viewCompras.setVisible(false);
    }
    
    private void isMaximizedResizeColumns(){
        
        if (!(getExtendedState() == MAXIMIZED_BOTH)){
            viewCompras.getTblCompras().setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            viewProduto.getTblProdutos().setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        } else{
            viewCompras.getTblCompras().setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            viewProduto.getTblProdutos().setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        }
    }
    
    private void isNotMaximizedThenExecutePack(){
        if (!(getExtendedState() == MAXIMIZED_BOTH)){
            pack();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBox = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_Clientes = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btn_Produtos = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btn_Compras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });

        panelBox.setLayout(new javax.swing.BoxLayout(panelBox, javax.swing.BoxLayout.LINE_AXIS));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btn_Clientes.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/clientes32.png"))); // NOI18N
        btn_Clientes.setToolTipText("Clientes");
        btn_Clientes.setBorder(null);
        btn_Clientes.setFocusable(false);
        btn_Clientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Clientes.setMargin(new java.awt.Insets(5, 7, 5, 7));
        btn_Clientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_Clientes);

        jSeparator1.setSeparatorSize(new java.awt.Dimension(5, 25));
        jToolBar1.add(jSeparator1);

        btn_Produtos.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/product32.png"))); // NOI18N
        btn_Produtos.setToolTipText("Produtos");
        btn_Produtos.setBorder(null);
        btn_Produtos.setFocusable(false);
        btn_Produtos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Produtos.setMargin(new java.awt.Insets(5, 7, 5, 7));
        btn_Produtos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProdutosActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_Produtos);

        jSeparator2.setSeparatorSize(new java.awt.Dimension(5, 25));
        jToolBar1.add(jSeparator2);

        btn_Compras.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_Compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/shopping_cart32.png"))); // NOI18N
        btn_Compras.setToolTipText("Vendas");
        btn_Compras.setBorder(null);
        btn_Compras.setFocusable(false);
        btn_Compras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Compras.setMargin(new java.awt.Insets(5, 7, 5, 7));
        btn_Compras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ComprasActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_Compras);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
            .addComponent(panelBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panelBox, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProdutosActionPerformed
        hideAllPanels();
        isMaximizedResizeColumns();
        viewProduto.getProdutoActionListener().populateJTableProdutos();
        viewProduto.setVisible(true);
        isNotMaximizedThenExecutePack();
    }//GEN-LAST:event_btn_ProdutosActionPerformed

    private void btn_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClientesActionPerformed
        hideAllPanels();
        viewCliente.getClienteActionListener().populateJTable();
        viewCliente.setVisible(true);
        isNotMaximizedThenExecutePack();
    }//GEN-LAST:event_btn_ClientesActionPerformed

    private void btn_ComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ComprasActionPerformed
        hideAllPanels();
        isMaximizedResizeColumns();
        viewCompras.setVisible(true);
        isNotMaximizedThenExecutePack();
    }//GEN-LAST:event_btn_ComprasActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
         isMaximizedResizeColumns();
    }//GEN-LAST:event_formWindowStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /*try {
                    UIManager.setLookAndFeel(
                        UIManager.getSystemLookAndFeelClassName());
                } catch (Exception useDefault) {}*/
                new ProgramFrm().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Clientes;
    private javax.swing.JButton btn_Compras;
    private javax.swing.JButton btn_Produtos;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel panelBox;
    // End of variables declaration//GEN-END:variables
}
