/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.windows;

import controller.listener.ProdutoActionListener;
import java.io.Serializable;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Lockland
 */
public class ViewProduto extends JPanel implements Serializable{

    // Create a tablemodel 
    // http://devsv.wordpress.com/2012/07/08/como-implementar-um-tablemodel/
    
    private ProdutoActionListener listener;
    
    /**
     * Creates new form ViewProduto
     */
    public ViewProduto() {
        initComponents();
        listener = new ProdutoActionListener(this);
        btn_prodSalvar.addActionListener( listener);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_prodTitulo = new javax.swing.JLabel();
        lbl_prodDescricao = new javax.swing.JLabel();
        llbl_prodPrecoUnitario = new javax.swing.JLabel();
        lbl_prodTarifa = new javax.swing.JLabel();
        txt_prodTitulo = new javax.swing.JTextField();
        txt_prodDescricao = new javax.swing.JTextField();
        txt_prodPrecoUnitario = new javax.swing.JTextField();
        txt_prodTarifa = new javax.swing.JTextField();
        btn_prodSalvar = new javax.swing.JButton();
        lbl_prodQuantidade = new javax.swing.JLabel();
        txt_prodQuantidade = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")), "Cadastro de Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lbl_prodTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_prodTitulo.setText("Titulo:");

        lbl_prodDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_prodDescricao.setText("Descrição:");

        llbl_prodPrecoUnitario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        llbl_prodPrecoUnitario.setText("Preço Unitário:");

        lbl_prodTarifa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_prodTarifa.setText("Tarifa:");

        btn_prodSalvar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_prodSalvar.setText("Salvar");

        lbl_prodQuantidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_prodQuantidade.setText("Quantidade:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(llbl_prodPrecoUnitario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_prodTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_prodDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_prodTarifa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbl_prodQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_prodTitulo)
                    .addComponent(txt_prodDescricao)
                    .addComponent(txt_prodPrecoUnitario)
                    .addComponent(txt_prodTarifa)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_prodSalvar)
                        .addGap(0, 71, Short.MAX_VALUE))
                    .addComponent(txt_prodQuantidade))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_prodTitulo)
                    .addComponent(txt_prodTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_prodDescricao)
                    .addComponent(txt_prodDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(llbl_prodPrecoUnitario)
                    .addComponent(txt_prodPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_prodTarifa)
                    .addComponent(txt_prodTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_prodQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_prodQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_prodSalvar)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public ProdutoActionListener getProdutoActionListener() {
        return listener;
    }

    public JButton getBtn_prodSalvar() {
        return btn_prodSalvar;
    }

    public void setBtn_prodSalvar(JButton btn_prodSalvar) {
        this.btn_prodSalvar = btn_prodSalvar;
    }

    public JTable getTblProdutos() {
        return tblProdutos;
    }

    public void setTblProdutos(JTable tblProdutos) {
        this.tblProdutos = tblProdutos;
    }

    public JTextField getTxt_prodDescricao() {
        return txt_prodDescricao;
    }

    public void setTxt_prodDescricao(JTextField txt_prodDescricao) {
        this.txt_prodDescricao = txt_prodDescricao;
    }

    public JTextField getTxt_prodPrecoUnitario() {
        return txt_prodPrecoUnitario;
    }

    public void setTxt_prodPrecoUnitario(JTextField txt_prodPrecoUnitario) {
        this.txt_prodPrecoUnitario = txt_prodPrecoUnitario;
    }

    public JTextField getTxt_prodQuantidade() {
        return txt_prodQuantidade;
    }

    public void setTxt_prodQuantidade(JTextField txt_prodQuantidade) {
        this.txt_prodQuantidade = txt_prodQuantidade;
    }

    public JTextField getTxt_prodTarifa() {
        return txt_prodTarifa;
    }

    public void setTxt_prodTarifa(JTextField txt_prodTarifa) {
        this.txt_prodTarifa = txt_prodTarifa;
    }

    public JTextField getTxt_prodTitulo() {
        return txt_prodTitulo;
    }

    public void setTxt_prodTitulo(JTextField txt_prodTitulo) {
        this.txt_prodTitulo = txt_prodTitulo;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_prodSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_prodDescricao;
    private javax.swing.JLabel lbl_prodQuantidade;
    private javax.swing.JLabel lbl_prodTarifa;
    private javax.swing.JLabel lbl_prodTitulo;
    private javax.swing.JLabel llbl_prodPrecoUnitario;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txt_prodDescricao;
    private javax.swing.JTextField txt_prodPrecoUnitario;
    private javax.swing.JTextField txt_prodQuantidade;
    private javax.swing.JTextField txt_prodTarifa;
    private javax.swing.JTextField txt_prodTitulo;
    // End of variables declaration//GEN-END:variables
}
